function DataTable = aquariusGetData(Host, SiteId, DataId, FromDate, ToDate, ...
                                     AuthToken, TimeZoneOutput, Username, Password)
%AQUARIUSGETDATA Get data from the Aquarius server
%   DataTable = AQUARIUSGETDATA(Host, SiteId, DataId, FromDate, ToDate, ...
%                               AuthToken, Username, Password)
%   Host = the location of the aquarius server 
%   SiteId = SiteId ("Identifier") for the site of interest. Note that 
%            SiteId should be given as a string.
%   DataId = The name of the dataset. Use GetDataSetsList to find out
%            what the exact DataId you want is.
%   AuthToken = Optional AuthToken generated by getAuthToken
%   TimeZoneOutput = timezone for the output data. 
%                    Optional, Default = "+12:00". See datetime for
%                    list of viable uinput formats.
%   Username, Password = Optional, only used if authToken is not supplied
%                        If neither AuthToken or Username/Password are 
%                        supplied the user will be prompted to input their
%                        Aquarius Username and Password.
%   
%   Data is returned as a dataframe with the timestamp as the index.
%   
%   e.g. TimeseriesData = getData('aquarius.niwa.co.nz', '65119', 'HG.Master', 
%                                 datetime.datetime.now()-datetime.timedelta(7))
%
%   See also: DATETIME, AQUARIUSGETAUTHTOKEN, AQUARIUSGETLOCATIONS,
%   AQUARIUSLISTDATASETS

if ~exist('AuthToken','var') || isempty(AuthToken)
    AuthToken = aquariusGetAuthToken(Host, Username, Password);
end

if ~exist('TimeZoneOutput', 'var') || isempty(TimeZoneOutput)
    TimeZoneOutput = "+12:00";
end
    
%% Build the request string
DateFormat = 'yyyy-mm-ddTHH:MM:SS.FFF';
FullDataID = sprintf('%s@%i', DataId, SiteId);
RequestString = sprintf('GetTimeSeriesData?token=%s&dataId=%s', ...
                        AuthToken, FullDataID);
if exist('FromDate','var') && ~isempty(FromDate)
    RequestString = sprintf('%s&queryFrom=%s', RequestString, ...
                            datestr(FromDate, DateFormat));
end
if exist('ToDate','var') && ~isempty(ToDate)
    RequestString = sprintf('%s&queryTo=%s', RequestString, ...
                            datestr(ToDate, DateFormat));
end
RequestString = [RequestString, '&returnFullCoverage=False', ...
                 '&includeGapMarkers=True'];

%% Get the data
AquariusURL = ['http://',Host,'/AQUARIUS/Publish/AquariusPublishRestService.svc/'];
myReadTable = @(filename)readtable(filename,'ReadVariableNames',true, ...
                                   'Delimiter',',','HeaderLines',4);
Options = weboptions('ContentReader',myReadTable);

DataTable = webread([AquariusURL,RequestString], Options);

%% Convert the Time field to a datetime format
DataTable.Time = datetime(DataTable.Time, ...
                          'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss.SSSZ', ...
                          'TimeZone', TimeZoneOutput);


end