function DatasetTable = aquariusListDatasets(Host, SiteId, AuthToken, ...
                                             Username, Password)
% AQUARIUSLISTDATASETS List of datasets available for a specified site.
%   Host = the location of the aquarius server 
%   SiteId = SiteId ("Identifier") for the site of interest. Note that 
%            SiteId should be given as a string.
%   AuthToken = Optional AuthToken generated by getAuthToken
%   Username, Password = Optional, only used if authToken is not supplied
%                        If neither AuthToken or Username/Password are 
%                        supplied the user will be prompted to input their
%                        Aquarius Username and Password.
%   
%   e.g. AvailableDatasets = getLocations('aquarius.niwa.co.nz', '65119')

    
if ~exist('AuthToken','var') || isempty(AuthToken)
    AuthToken = aquariusGetAuthToken(Host, Username, Password);
end

RequestString = sprintf('GetDataSetsList?token=%s&locId=%i', AuthToken, SiteId);
                               
AquariusURL = ['http://',Host,'/AQUARIUS/Publish/AquariusPublishRestService.svc/'];
myReadTable = @(filename)readtable(filename,'ReadVariableNames',true, ...
                                   'Delimiter',',');
Options = weboptions('ContentReader',myReadTable);

DatasetTable = webread([AquariusURL,RequestString], Options);

end