%% WAVESUMMARY summarise wave data and produce wave rose for paper


%% Setup

% Add required directories (and subdirectories)
addpath(genpath('functions'))
addpath(genpath('inputs'))

% Read input parameters
Config = HurunuiAnalysisConfig;

%% Read model wave data
WaveModTS = readtable(fullfile(Config.DataFolder,Config.WaveModelOutput), ...
                      'HeaderLines',27,...
                      'ReadVariableNames',false ,...
                      'Format', '%f%d%d%d%d%d%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f');
WaveModTS.Var2 = datetime([WaveModTS{:,2:6}, zeros(height(WaveModTS),1)]);
WaveModTS(:,[1,3:6,24:25]) = [];
WaveModTS.Properties.VariableNames = {'DateTime', ...
                                      'Hsig', ...
                                      'Tm01', ...
                                      'Tm02', ...
                                      'RTpeak', ...
                                      'Dir', ...
                                      'Dspr', ...
                                      'PkDir', ...
                                      'XWindv', ...
                                      'YWindv', ...
                                      'Ubot', ...
                                      'Urms', ...
                                      'Wlen', ...
                                      'Depth', ...
                                      'XTransp', ...
                                      'YTransp', ...
                                      'XWForce', ...
                                      'YWForce'};

%% Calculate stats

% mean
fprintf('Mean significant wave height = %1.2f\n', mean(WaveModTS.Hsig))

% mean annual max
WaveModTS.Year = year(WaveModTS.DateTime);
YearList = unique(WaveModTS.Year);
YearList = YearList(2:end-1); %get rid of part years
YearlyMaxHs = NaN(size(YearList));
for ii = 1:size(YearList,1)
    YearlyMaxHs(ii) = max(WaveModTS.Hsig(WaveModTS.Year==YearList(ii)));
end
fprintf('Mean annual maximum Hs = %1.2f\n', mean(YearlyMaxHs))
